version: '3.7'

services:
    php-8:
        hostname: fpdbtest
        container_name: fpdbtest_php
        build: ./docker/
        volumes:
            - .:/app
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        environment:
            PHP_IDE_CONFIG: serverName=Docker
            XDEBUG_CONFIG: "client_host=host.docker.internal log_level=0 log=/tmp/xdebug.log"
        networks:
            - backend

# Networks Setup
networks:
    backend:
        driver: bridge
        ipam:
            driver: default
            config:
                -   subnet: 192.168.32.0/28